"""add flutterwave fields to payments

Revision ID: 54dbfd8ad1bb
Revises: 70de6774920f
Create Date: 2026-03-17 21:46:22.504833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54dbfd8ad1bb'
down_revision: Union[str, None] = '70de6774920f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tx_ref', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('flw_tx_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'payments', ['tx_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'flw_tx_id')
    op.drop_column('payments', 'tx_ref')
    # ### end Alembic commands ###
