"""add mpesa fields to payments

Revision ID: 70de6774920f
Revises: 75e6aa6f5f60
Create Date: 2026-03-17 01:05:01.872523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70de6774920f'
down_revision: Union[str, None] = '75e6aa6f5f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('checkout_request_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('mpesa_receipt', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payments', ['checkout_request_id'])
    op.create_unique_constraint(None, 'payments', ['mpesa_receipt'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'mpesa_receipt')
    op.drop_column('payments', 'checkout_request_id')
    op.drop_column('payments', 'phone')
    # ### end Alembic commands ###
