"""added uid columns to address and payment tables

Revision ID: aae80b89b023
Revises: 2b78e76ed87a
Create Date: 2026-03-15 00:38:46.799260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae80b89b023'
down_revision: Union[str, None] = '2b78e76ed87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_addresses_uid'), 'addresses', ['uid'], unique=True)
    op.add_column('payments', sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_payments_uid'), 'payments', ['uid'], unique=True)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('TRUE'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_payments_uid'), table_name='payments')
    op.drop_column('payments', 'uid')
    op.drop_index(op.f('ix_addresses_uid'), table_name='addresses')
    op.drop_column('addresses', 'uid')
    # ### end Alembic commands ###
