"""added driver id and restuarant id columns to order tables

Revision ID: fbb8472b2a78
Revises: aae80b89b023
Create Date: 2026-03-15 01:34:19.568155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb8472b2a78'
down_revision: Union[str, None] = 'aae80b89b023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['driver_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'restaurants', ['restaurant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'restaurant_id')
    op.drop_column('orders', 'driver_id')
    # ### end Alembic commands ###
